### PR TITLE
Version Update to 4.1.0

### PR DESCRIPTION
**Pull request by faizankarim**
Version updated to 4.1.0

### CODE REVIEW

**Comment by philipperemy** [comment]
@faizankarim Does https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip work for you? They have a very bad proxy at Stanford..

**Comment by philipperemy** [comment]
```
wget https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
--2020-08-12 23:19:34--  https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443...
```

**Comment by faizankarim** [comment]
Yes it worked on my local machine and on cloud too..

**Comment by faizankarim** [comment]
> ```
> wget https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
> --2020-08-12 23:19:34--  https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
> Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
> Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443...
> ```

let me test it...

**Comment by faizankarim** [comment]
> ```
> wget https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
> --2020-08-12 23:19:34--  https://nlp.stanford.edu/software/stanford-corenlp-4.1.0.zip
> Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
> Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443...
> ```

failing with wget but working with code, tested again.

**Comment by philipperemy** [comment]
Ok now the link seems to work.

**Comment by philipperemy** [comment]
@faizankarim do you know if OpenIE works with other languages than english by the way?

**Pull request merged**
